# Generated by Django 3.0.1 on 2020-03-06 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expensecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensecategory_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '支出カテゴリ',
                'verbose_name_plural': '支出カテゴリ',
                'db_table': 'expensecategory',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensedate', models.DateField(default=datetime.datetime.now, verbose_name='日付')),
                ('expensemoney', models.IntegerField(help_text='単位は日本円', verbose_name='金額')),
                ('expensememo', models.CharField(max_length=500, verbose_name='メモ')),
                ('expensecategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense.Expensecategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'db_table': 'expense',
            },
        ),
    ]
