# Generated by Django 3.0.1 on 2020-03-06 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incomecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomecategory_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '収入カテゴリ',
                'verbose_name_plural': '収入カテゴリ',
                'db_table': 'incomecategory',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomedate', models.DateField(default=datetime.datetime.now, verbose_name='日付')),
                ('incomemoney', models.IntegerField(help_text='単位は日本円', verbose_name='金額')),
                ('incomememo', models.CharField(max_length=500, verbose_name='メモ')),
                ('incomecategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income.Incomecategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '収入',
                'verbose_name_plural': '収入',
                'db_table': 'income',
            },
        ),
    ]
