# Generated by Django 3.0.3 on 2020-02-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(verbose_name='達成状況')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
            ],
            options={
                'verbose_name': 'トロフィー',
                'verbose_name_plural': 'トロフィー',
                'db_table': 'trophy',
            },
        ),
    ]
