# Generated by Django 3.0.3 on 2020-02-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophy',
            old_name='content',
            new_name='trophycontent',
        ),
        migrations.RenameField(
            model_name='trophy',
            old_name='done',
            new_name='trophydone',
        ),
    ]
